<?php
ob_start();
$articleList = $this->getVar('articleList');
foreach ($articleList as $article):
?>
<article id="post-1417" class="post-1417 post type-post status-publish format-standard hentry category-opengl-es-api tag-api tag-opengl et_pb_post">
	<h2><a href="<?php $this->sEcho($article[DWModuleFrontuiArticle::ArticleUrlKey]);?>"><?php $this->sEcho($article[DWModelArticle::TablePostColumnTitle]);?></a></h2>
	<p class="post-meta">
        <span class="dw_post_meta_element dw_post_meta_element_time"><time><?php $this->sEcho($article[DWModelArticle::TablePostColumnDate]);?></time></span>
        <span class="dw_post_meta_element dw_post_meta_element_author"><?php $this->sEcho($article[DWModelUser::TableUsersColumnDisplayName]);?></span>
        <?php
        if ($article['categories']):
            foreach ($article['categories'] as $category):
                ?>
                <a class="dw_post_meta_element dw_post_meta_element_category" href="<?php echo $category['url'];?>" title="<?php echo $category[DWModelTerm::TableTermTaxonomyColumnDescription]; ?>" rel="category"><?php echo $category[DWModelTerm::TableTermColumnName]; ?></a>
        <?php
            endforeach;
        else:
            $cate = $this->getVar('cate');
            if ($cate):
        ?>
                <a class="dw_post_meta_element dw_post_meta_element_category" href="<?php $this->sEcho($cate[DWModelTerm::CategoryKeyUrl]);?>" title="<?php $this->sEcho($cate[DWModelTerm::TableTermTaxonomyColumnDescription]); ?>" rel="category"><?php $this->sEcho($cate[DWModelTerm::TableTermColumnName]); ?></a>
        <?php
            endif;
        endif;
        ?>
    </p>
	<p><?php echo $article[DWModelArticle::TablePostColumnDigest];?></p>
    <?php if ($article['tags']): ?>
    <footer>
        <span class="dw-tag-links">
        <?php foreach ($article['tags'] as $tag): ?>
            <a href="<?php $this->sEcho($tag['url']);?>" title="<?php $this->sEcho($tag[DWModelTerm::TableTermColumnName]); ?>" rel="tag"><?php $this->sEcho($tag[DWModelTerm::TableTermColumnName]); ?></a>
        <?php endforeach; ?>
        </span>
    </footer>
    <?php endif; ?>
</article><!-- .et_pb_post -->
<?php
endforeach;
$html = ob_get_clean();

$response = array(
    'status' => $this->getVar('status'),
    'requestCount' => $this->getVar('requestCount'),
    'returnCount' => $this->getVar('returnCount'),
    'noMoreData' => $this->getVar('noMoreData'),
    'content' => $html,
    );
echo json_encode($response);