<div id="respond" class="comment-respond dw_state_active">
    <h3 id="reply-title" class="comment-reply-title"><span><?php $this->sEchoI18n('Submit a Comment'); ?></span> <small><a rel="nofollow" id="cancel-comment-reply-link" href="#respond" style="display: none;"><?php $this->sEchoI18n('Cancel reply'); ?></a></small></h3>

    <form action="<?php echo $this->getVar('formActionUrl'); ?>" method="post" id="commentform" class="comment-form">
        <p class="comment-form-author"><label for="author"><?php $this->sEchoI18n('Name'); ?> <span class="required">*</span></label> <input id="author" name="author" type="text" value="" size="30" aria-required="true"></p>
        <p class="comment-form-email"><label for="email">Email(<?php $this->sEchoI18n('will not be published'); ?>, <?php $this->sEchoI18n('used for generate avatar'); ?>)</span></label> <input id="email" name="email" type="text" value="" size="30"></p>
        <p class="comment-form-url"><label for="url"><?php $this->sEchoI18n('Website'); ?></label> <input id="url" name="url" type="text" value="" size="30"></p>
        <p class="comment-form-comment"><label for="comment"><?php $this->sEchoI18n('Comment'); ?> <span class="required">*</span></label> <textarea id="comment" name="comment" cols="45" rows="8" aria-required="true"></textarea></p>
        <!--<p class="form-allowed-tags">You may use these <abbr title="HyperText Markup Language">HTML</abbr> tags and attributes:  <code>&lt;a href="" title=""&gt; &lt;abbr title=""&gt; &lt;acronym title=""&gt; &lt;b&gt; &lt;blockquote cite=""&gt; &lt;cite&gt; &lt;code&gt; &lt;del datetime=""&gt; &lt;em&gt; &lt;i&gt; &lt;q cite=""&gt; &lt;strike&gt; &lt;strong&gt; </code></p>-->
        <p id="dw_human_check" class="dw_human_check clearfix">
            <?php
            $humanCheckInfo = $this->getVar('humanCheckInfo');
            $colorList = $humanCheckInfo['colors'];
            $checkList = $humanCheckInfo['check'];
            foreach ($colorList as $idx => $color) :
            ?>
            <span style="background-color:#<?php echo $color; ?>;" value="<?php echo $checkList[$idx]; ?>"></span>
            <?php endforeach; ?>
        </p>
        <p class="dw_form_error_prompt"><?php $this->sEchoI18n('Please pick the block with different color(warm/cold), then submit'); ?></p>
        <p class="form-submit">
            <input name="submit" type="submit" id="submit" value="<?php $this->sEchoI18n('Submit Comment'); ?>">
            <input type="hidden" name="comment_post_ID" value="0" id="comment_post_ID">
            <input type="hidden" name="comment_parent" id="comment_parent" value="0">
            <input type="hidden" name="human_check_hash" id="human_check_hash" value="<?php echo $humanCheckInfo['code']; ?>">
            <input type="hidden" name="human_check_value" id="human_check_value" value="">
        </p>
    </form>
    <div class="block-cover"></div>
</div>