<!DOCTYPE html>
<!--[if IE 6]>
<html id="ie6" class="ie" lang="<?php echo LANG; ?>" ieversion="6" alerturl="/frontui/common/ajaxiealert">
<![endif]-->
<!--[if IE 7]>
<html id="ie7" class="ie" lang="<?php echo LANG; ?>" ieversion="7" alerturl="/frontui/common/ajaxiealert">
<![endif]-->
<!--[if IE 8]>
<html id="ie8" class="ie" lang="<?php echo LANG; ?>" ieversion="8" alerturl="/frontui/common/ajaxiealert">
<![endif]-->
<!--[if !(IE 6) | !(IE 7) | !(IE 8)  ]><!-->
<html lang="<?php echo LANG; ?>">
<!--<![endif]-->